customer:
    resource: "@TeleComBundle/Controller/CustomerController.php"
    prefix: /customer
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
